using System.Buffers.Binary;
using System.IO;
using System.Text;

namespace Errorly;

/// <summary>Serializes and validates the versioned Errorly incident package format.</summary>
public static class IncidentPackageSerializer
{
    private static ReadOnlySpan<byte> Magic=>"ERLYPKG1"u8;
    private static void WritePayload(BinaryWriter writer,ReadOnlyMemory<byte> payload)
    {
#if NETFRAMEWORK
        writer.Write(payload.ToArray());
#else
        writer.Write(payload.Span);
#endif
    }
    public static byte[] Serialize(IncidentPackage package)
    {
        if(package is null)throw new ArgumentNullException(nameof(package));Validate(package);
        using var stream=new MemoryStream();using var writer=new BinaryWriter(stream,Encoding.UTF8,true);
        writer.Write(Magic.ToArray());writer.Write(IncidentPackage.SchemaVersion);writer.Write((ushort)0);writer.Write(package.IncidentId.ToByteArray());writer.Write(package.CreatedUtc.UtcDateTime.Ticks);writer.Write(package.SessionId.ToByteArray());writer.Write((byte)package.ReportType);writer.Write((byte)0);writer.Write((ushort)0);WriteString(writer,package.ApplicationId);WriteString(writer,package.Environment);WriteString(writer,package.ApplicationVersion);WriteString(writer,package.ReportMessage);writer.Write(package.QpcFrequency);writer.Write(package.QpcAnchor);writer.Write(package.UtcAnchorFileTime);writer.Write(package.StartTicks);writer.Write(package.EndTicks);writer.Write((uint)package.Records.Count);
        foreach(var record in package.Records){writer.Write(record.Type);writer.Write(record.Flags);writer.Write(record.Sequence);writer.Write(record.Timestamp);writer.Write(record.WindowId);writer.Write(record.Width);writer.Write(record.Height);writer.Write(record.Provider);writer.Write(record.ResolutionTier);writer.Write((uint)record.Payload.Length);WritePayload(writer,record.Payload);if(stream.Length>IncidentPackageLimits.MaximumPackageBytes)throw new InvalidDataException("Incident package exceeds its size limit.");}
        WriteString(writer,package.SourceRevision);writer.Write((uint)package.Exceptions.Count);foreach(var exception in package.Exceptions){WriteString(writer,exception.Type);WriteString(writer,exception.RawStackTrace);writer.Write((uint)exception.Frames.Count);foreach(var frame in exception.Frames){writer.Write(frame.Index);WriteString(writer,frame.Method);WriteString(writer,frame.DeclaringType);WriteString(writer,frame.Assembly);WriteString(writer,frame.File);writer.Write(frame.Line??0);writer.Write(frame.Column??0);writer.Write((byte)frame.Classification);writer.Write((byte)frame.SourceAvailability);if(IncidentPackage.SchemaVersion>=4){writer.Write((frame.ModuleVersionId??Guid.Empty).ToByteArray());writer.Write(frame.MethodMetadataToken??0);writer.Write(frame.ILOffset??-1);writer.Write((frame.PortablePdbId??Guid.Empty).ToByteArray());}}}WriteString(writer,package.GroupingKey);WriteLogContext(writer,package.ApplicationLogContext);writer.Write(package.FreezeTicks??0);WriteRuntimeContext(writer,package.RuntimeContext);
        if(stream.Length>IncidentPackageLimits.MaximumPackageBytes)throw new InvalidDataException("Incident package exceeds its size limit.");
        return stream.ToArray();
    }
    public static IncidentPackage Deserialize(ReadOnlySpan<byte> bytes)
    {
        if(bytes.Length>IncidentPackageLimits.MaximumPackageBytes)throw new InvalidDataException("Incident package exceeds its size limit.");var reader=new Reader(bytes);
        if(!reader.ReadBytes(8).SequenceEqual(Magic))throw new InvalidDataException("Invalid incident package magic.");var version=reader.ReadUInt16();if(version is <1 or >IncidentPackage.SchemaVersion)throw new NotSupportedException($"Unsupported incident package schema {version}.");reader.ReadUInt16();var incidentId=new Guid(reader.ReadBytes(16).ToArray());var created=new DateTimeOffset(reader.ReadInt64(),TimeSpan.Zero);var sessionId=new Guid(reader.ReadBytes(16).ToArray());var reportType=(ErrorlyIncidentReportType)reader.ReadByte();reader.ReadByte();reader.ReadUInt16();var app=reader.ReadString();var environment=version>=2?reader.ReadString():null;var applicationVersion=version>=5?reader.ReadString():null;var message=reader.ReadString();var frequency=reader.ReadUInt64();var anchor=reader.ReadUInt64();var utc=reader.ReadInt64();var start=reader.ReadUInt64();var end=reader.ReadUInt64();var count=reader.ReadUInt32();if(count>IncidentPackageLimits.MaximumRecords)throw new InvalidDataException("Too many incident records.");
        var records=new List<IncidentPackageRecord>((int)count);var frames=0;ulong prior=0;for(var i=0u;i<count;i++){var type=reader.ReadUInt32();var flags=reader.ReadUInt32();var sequence=reader.ReadUInt64();var ticks=reader.ReadUInt64();var window=reader.ReadUInt64();var width=reader.ReadUInt32();var height=reader.ReadUInt32();var provider=reader.ReadUInt32();var tier=reader.ReadUInt32();var length=reader.ReadUInt32();if(length>IncidentPackageLimits.MaximumRecordPayloadBytes)throw new InvalidDataException("Record payload exceeds its size limit.");if(sequence==0||sequence<=prior)throw new InvalidDataException("Record sequence is invalid.");prior=sequence;if(type==1&&++frames>IncidentPackageLimits.MaximumFrames)throw new InvalidDataException("Too many frames.");if(type==1&&length>IncidentPackageLimits.MaximumJpegBytes)throw new InvalidDataException("JPEG exceeds its size limit.");var payload=reader.ReadBytes(checked((int)length)).ToArray();records.Add(new(type,flags,sequence,ticks,window,width,height,provider,tier,payload));}
        string? sourceRevision=null;var exceptions=new List<ErrorlyExceptionInfo>();if(version>=3){sourceRevision=reader.ReadString();var exceptionCount=reader.ReadUInt32();if(exceptionCount>8)throw new InvalidDataException("Too many exceptions.");for(var i=0u;i<exceptionCount;i++){var type=reader.ReadString()??throw new InvalidDataException("Exception type is missing.");var stack=reader.ReadString();var frameCount=reader.ReadUInt32();if(frameCount>IncidentPackageLimits.MaximumStackFrames)throw new InvalidDataException("Too many stack frames.");var exceptionFrames=new List<ErrorlyStackFrame>((int)frameCount);for(var j=0u;j<frameCount;j++){var index=reader.ReadInt32();var method=reader.ReadString();var declaringType=reader.ReadString();var assembly=reader.ReadString();var file=reader.ReadString();var line=reader.ReadInt32();var column=reader.ReadInt32();var classification=(ErrorlyStackFrameClassification)reader.ReadByte();var availability=(ErrorlySourceAvailability)reader.ReadByte();var moduleVersionId=version>=4?new Guid(reader.ReadBytes(16).ToArray()):Guid.Empty;var methodMetadataToken=version>=4?reader.ReadInt32():0;var ilOffset=version>=4?reader.ReadInt32():-1;var portablePdbId=version>=4?new Guid(reader.ReadBytes(16).ToArray()):Guid.Empty;exceptionFrames.Add(new(index,method,declaringType,assembly,file,line==0?null:line,column==0?null:column,classification,availability,moduleVersionId==Guid.Empty?null:moduleVersionId,methodMetadataToken==0?null:methodMetadataToken,ilOffset<0?null:ilOffset,portablePdbId==Guid.Empty?null:portablePdbId));}exceptions.Add(new(type,stack,exceptionFrames));}}
        var groupingKey=version>=6?reader.ReadString():null;var logContext=version>=7?ReadLogContext(ref reader):null;var freezeTicks=version>=9?reader.ReadUInt64():0;var runtimeContext=version>=10?ReadRuntimeContext(ref reader):null;if(!reader.AtEnd)throw new InvalidDataException("Unexpected trailing package data.");var package=new IncidentPackage(incidentId,created,app,environment,sessionId,reportType,message,frequency,anchor,utc,start,end,records,sourceRevision,exceptions,applicationVersion,groupingKey,logContext,freezeTicks==0?null:freezeTicks,runtimeContext);Validate(package);return package;
    }
    private static void Validate(IncidentPackage package){if(package.IncidentId==Guid.Empty||package.SessionId==Guid.Empty||package.CreatedUtc.Offset!=TimeSpan.Zero||package.ReportType!=ErrorlyIncidentReportType.Problem||package.QpcFrequency==0||package.EndTicks<package.StartTicks||package.Records.Count>IncidentPackageLimits.MaximumRecords||package.Exceptions.Count>8)throw new InvalidDataException("Incident metadata is invalid.");var frames=0;ulong prior=0;foreach(var record in package.Records){if(record.Payload.Length>IncidentPackageLimits.MaximumRecordPayloadBytes)throw new InvalidDataException("Record payload exceeds its size limit.");if(record.Sequence==0||record.Sequence<=prior)throw new InvalidDataException("Record ordering is invalid.");prior=record.Sequence;if(record.Type==1){frames++;if(record.Payload.Length>IncidentPackageLimits.MaximumJpegBytes)throw new InvalidDataException("JPEG exceeds its size limit.");}}if(frames>IncidentPackageLimits.MaximumFrames)throw new InvalidDataException("Too many frames.");ValidateString(package.ApplicationId);ValidateString(package.ApplicationVersion);ValidateString(package.SourceRevision);IncidentEnvironment.Normalize(package.Environment);ValidateString(package.ReportMessage);foreach(var exception in package.Exceptions){ValidateString(exception.Type);ValidateString(exception.RawStackTrace);if(exception.Frames.Count>IncidentPackageLimits.MaximumStackFrames)throw new InvalidDataException("Too many stack frames.");foreach(var frame in exception.Frames){ValidateString(frame.Method);ValidateString(frame.DeclaringType);ValidateString(frame.Assembly);ValidateString(frame.File);}}ValidateLogContext(package.ApplicationLogContext);ValidateRuntimeContext(package.RuntimeContext);
    }
    private static void ValidateLogContext(IncidentLogContext? context){if(context is null)return;if(context.Version!=IncidentLogContext.CurrentVersion||context.Entries.Count>IncidentPackageLimits.MaximumLogEntries||context.ProcessId<0)throw new InvalidDataException("Incident log context is invalid.");var bytes=0;ulong previous=0;foreach(var entry in context.Entries){if(entry.Timestamp.Offset!=TimeSpan.Zero||entry.Sequence==0||entry.Sequence<=previous||!Enum.IsDefined(typeof(IncidentLogLevel),entry.Level)||entry.Properties.Count>IncidentPackageLimits.MaximumLogProperties)throw new InvalidDataException("Incident log entry is invalid.");previous=entry.Sequence;var entryBytes=8+8+1;foreach(var value in new[]{entry.Category,entry.MessageTemplate,entry.RenderedMessage,entry.ExceptionType,entry.ExceptionMessage}){ValidateString(value);entryBytes+=StringBytes(value);}foreach(var property in entry.Properties){if(string.IsNullOrWhiteSpace(property.Name)||StringBytes(property.Name)>IncidentPackageLimits.MaximumLogPropertyBytes||StringBytes(property.Value)>IncidentPackageLimits.MaximumLogPropertyBytes)throw new InvalidDataException("Incident log property is invalid.");entryBytes+=StringBytes(property.Name)+StringBytes(property.Value);}if(entryBytes>IncidentPackageLimits.MaximumLogEntryBytes)throw new InvalidDataException("Incident log entry exceeds its size limit.");bytes+=entryBytes;if(bytes>IncidentPackageLimits.MaximumLogContextBytes)throw new InvalidDataException("Incident log context exceeds its size limit.");}}
    private static void ValidateRuntimeContext(IncidentRuntimeContext? context)
    {
        if(context is null)return;
        if(context.SchemaVersion!=1)throw new InvalidDataException("Unsupported runtime context version.");
        var bytes=0;foreach(var value in context.Values){var length=StringBytes(value);if(length>256)throw new InvalidDataException("Runtime context field exceeds its size limit.");bytes+=length;}
        if(bytes>4096)throw new InvalidDataException("Runtime context exceeds its size limit.");
    }
    private static void WriteRuntimeContext(BinaryWriter writer,IncidentRuntimeContext? context)
    {writer.Write(context is null?(byte)0:(byte)1);if(context is null)return;writer.Write(context.SchemaVersion);foreach(var value in context.Values)WriteString(writer,value);}
    private static IncidentRuntimeContext? ReadRuntimeContext(ref Reader reader)
    {var marker=reader.ReadByte();if(marker==0)return null;if(marker!=1)throw new InvalidDataException("Invalid runtime context marker.");return new(reader.ReadInt32(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString(),reader.ReadString());}
    private static int StringBytes(string? value)=>value is null?0:Encoding.UTF8.GetByteCount(value);
    private static void WriteLogContext(BinaryWriter writer,IncidentLogContext? context){writer.Write(context is null?(byte)0:(byte)1);if(context is null)return;writer.Write(context.Version);writer.Write((byte)((context.RateLimited?1:0)|(context.Truncated?2:0)));writer.Write(context.DroppedEntryCount);writer.Write(context.ProcessId);writer.Write((uint)context.Entries.Count);foreach(var entry in context.Entries){writer.Write(entry.Timestamp.UtcDateTime.Ticks);writer.Write(entry.Sequence);writer.Write((byte)entry.Level);WriteString(writer,entry.Category);WriteString(writer,entry.MessageTemplate);WriteString(writer,entry.RenderedMessage);WriteString(writer,entry.ExceptionType);WriteString(writer,entry.ExceptionMessage);writer.Write((uint)entry.Properties.Count);foreach(var property in entry.Properties){WriteString(writer,property.Name);WriteString(writer,property.Value);}}}
    private static IncidentLogContext? ReadLogContext(ref Reader reader){var present=reader.ReadByte();if(present==0)return null;if(present!=1)throw new InvalidDataException("Incident log context marker is invalid.");var version=reader.ReadByte();var flags=reader.ReadByte();if((flags&~3)!=0)throw new InvalidDataException("Incident log context flags are invalid.");var dropped=reader.ReadUInt32();var processId=reader.ReadInt32();var count=reader.ReadUInt32();if(count>IncidentPackageLimits.MaximumLogEntries)throw new InvalidDataException("Too many incident log entries.");var entries=new List<IncidentLogEntry>((int)count);for(var i=0u;i<count;i++){var timestamp=new DateTimeOffset(reader.ReadInt64(),TimeSpan.Zero);var sequence=reader.ReadUInt64();var level=(IncidentLogLevel)reader.ReadByte();var category=reader.ReadString();var template=reader.ReadString();var rendered=reader.ReadString();var exceptionType=reader.ReadString();var exceptionMessage=reader.ReadString();var propertyCount=reader.ReadUInt32();if(propertyCount>IncidentPackageLimits.MaximumLogProperties)throw new InvalidDataException("Too many incident log properties.");var properties=new List<IncidentLogProperty>((int)propertyCount);for(var j=0u;j<propertyCount;j++)properties.Add(new(reader.ReadString()??throw new InvalidDataException("Incident log property name is missing."),reader.ReadString()??throw new InvalidDataException("Incident log property value is missing.")));entries.Add(new(timestamp,sequence,level,category,template,rendered,exceptionType,exceptionMessage,properties));}return new(entries,dropped,(flags&1)!=0,(flags&2)!=0,processId,version);}
    private static void ValidateString(string? value){if(value is not null&&Encoding.UTF8.GetByteCount(value)>IncidentPackageLimits.MaximumStringBytes)throw new InvalidDataException("Incident string exceeds its size limit.");}
    private static void WriteString(BinaryWriter writer,string? value){if(value is null){writer.Write(uint.MaxValue);return;}var bytes=Encoding.UTF8.GetBytes(value);writer.Write((uint)bytes.Length);writer.Write(bytes);}
    private ref struct Reader{private ReadOnlySpan<byte> source;private int offset;internal Reader(ReadOnlySpan<byte> source){this.source=source;offset=0;}internal bool AtEnd=>offset==source.Length;internal ReadOnlySpan<byte> ReadBytes(int length){if(length<0||length>source.Length-offset)throw new InvalidDataException("Incident package is truncated.");var value=source.Slice(offset,length);offset+=length;return value;}internal byte ReadByte()=>ReadBytes(1)[0];internal ushort ReadUInt16()=>BinaryPrimitives.ReadUInt16LittleEndian(ReadBytes(2));internal uint ReadUInt32()=>BinaryPrimitives.ReadUInt32LittleEndian(ReadBytes(4));internal int ReadInt32()=>BinaryPrimitives.ReadInt32LittleEndian(ReadBytes(4));internal ulong ReadUInt64()=>BinaryPrimitives.ReadUInt64LittleEndian(ReadBytes(8));internal long ReadInt64()=>BinaryPrimitives.ReadInt64LittleEndian(ReadBytes(8));internal string? ReadString(){var length=ReadUInt32();if(length==uint.MaxValue)return null;if(length>IncidentPackageLimits.MaximumStringBytes)throw new InvalidDataException("Incident string exceeds its size limit.");return Encoding.UTF8.GetString(ReadBytes((int)length).ToArray());}}
}


